version: '3.8'
services:
  petwemint_app:
    container_name: petwemint_app
    restart: always
    env_file: .env
    ports:
      - "5005:5005"
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - petwemint_app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 