# Generated by Django 4.0.1 on 2022-06-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pet'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
