# Generated by Django 4.0.1 on 2022-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pet_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftprepared',
            name='style',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
